import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tmpDir = path.join(__dirname, '..', 'tmp');
if (!fs.existsSync(tmpDir)) {
  fs.mkdirSync(tmpDir, { recursive: true });
}

const documentTitle = {
  deed: 'Land Deed Document',
  ownership_proof: 'Ownership Proof Document',
  other: 'Registry Document',
};

export const createFakeDocumentPdf = async (propertyId, docType, metadata = {}) => {
  const fileName = `${propertyId}-${docType}.pdf`;
  const filePath = path.join(tmpDir, fileName);
  const { ownerName = 'Government Registry', location = 'Odisha, India' } = metadata;
  const date = new Date().toISOString();

  await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fontSize(24).fillColor('#103a72').text('Bhumi Land Registry', { align: 'left' });
    doc.moveDown(0.5);
    doc.fontSize(18).fillColor('#1f3f77').text(documentTitle[docType] || documentTitle.other);
    doc.moveDown(1);

    doc.fontSize(12).fillColor('#000000');
    doc.text(`Property ID: ${propertyId}`);
    doc.text(`Document Type: ${docType}`);
    doc.text(`Owner Name: ${ownerName}`);
    doc.text(`Location: ${location}`);
    doc.text(`Generated by Bhumi data import script`);
    doc.text(`Timestamp: ${date}`);

    doc.moveDown(1);
    doc.fontSize(10).fillColor('#444444').text('This is a generated fake document for testing and IPFS upload.', { align: 'left' });

    doc.end();

    stream.on('finish', resolve);
    stream.on('error', reject);
    doc.on('error', reject);
  });

  return filePath;
};

export const cleanupFakeDocumentFile = (filePath) => {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  } catch (error) {
    console.warn('Could not remove temporary fake document file:', filePath, error.message);
  }
};
