import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tmpDir = path.join(__dirname, '..', 'tmp');
if (!fs.existsSync(tmpDir)) {
  fs.mkdirSync(tmpDir, { recursive: true });
}

const documentTitle = {
  deed: 'Land Deed Document',
  ownership_proof: 'Ownership Proof Document',
  other: 'Registry Document',
};

export const createFakeDocumentImage = (propertyId, docType, metadata = {}) => {
  const fileName = `${propertyId}-${docType}.svg`;
  const filePath = path.join(tmpDir, fileName);
  const { ownerName = 'Government Registry', location = 'Odisha, India' } = metadata;
  const date = new Date().toISOString();
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="840">
  <rect width="1200" height="840" fill="#ffffff"/>
  <rect x="30" y="30" width="1140" height="780" rx="28" ry="28" fill="#f7fbff" stroke="#2e4cab" stroke-width="12"/>
  <text x="60" y="110" font-family="Arial, sans-serif" font-size="52" fill="#103a72">Bhumi Land Registry</text>
  <text x="60" y="180" font-family="Arial, sans-serif" font-size="32" fill="#1f3f77">${documentTitle[docType] || documentTitle.other}</text>
  <text x="60" y="260" font-family="Arial, sans-serif" font-size="24" fill="#1f3f77">Property ID: ${propertyId}</text>
  <text x="60" y="300" font-family="Arial, sans-serif" font-size="24" fill="#1f3f77">Document Type: ${docType}</text>
  <text x="60" y="340" font-family="Arial, sans-serif" font-size="24" fill="#1f3f77">Owner Name: ${ownerName}</text>
  <text x="60" y="380" font-family="Arial, sans-serif" font-size="24" fill="#1f3f77">Location: ${location}</text>
  <text x="60" y="520" font-family="Arial, sans-serif" font-size="20" fill="#2d4f7c">Generated by Bhumi data import script</text>
  <text x="60" y="560" font-family="Arial, sans-serif" font-size="20" fill="#2d4f7c">Timestamp: ${date}</text>
  <line x1="60" y1="600" x2="1140" y2="600" stroke="#2e4cab" stroke-width="4"/>
  <text x="60" y="660" font-family="Arial, sans-serif" font-size="18" fill="#3b4c72">This is a fake document image generated for testing and IPFS upload.</text>
</svg>`;
  fs.writeFileSync(filePath, svg, 'utf8');
  return filePath;
};

export const cleanupFakeDocumentFile = (filePath) => {
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  } catch (error) {
    console.warn('Could not remove temporary fake document file:', filePath, error.message);
  }
};
